"""Add funding_goal and current_funding to FeaturedSchool

Revision ID: 0fcae27d4c56
Revises: 
Create Date: 2025-07-12 10:44:49.981786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fcae27d4c56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('featured_school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funding_goal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_funding', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('featured_school', schema=None) as batch_op:
        batch_op.drop_column('current_funding')
        batch_op.drop_column('funding_goal')

    # ### end Alembic commands ###
